# Generated by Django 4.2.11 on 2024-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_owner_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="DaysOfWeek",
            field=models.CharField(
                choices=[
                    ("OP", "Operator"),
                    ("SL", "Seller"),
                    ("PR", "President"),
                    ("TR", "Transport"),
                ],
                default="MON",
                max_length=20,
            ),
        ),
    ]
