# Generated by Django 4.2.11 on 2024-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_member_daysofweek"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="DaysOfWeek",
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("H", "High"), ("M", "Medium"), ("S", "Small")],
                default="M",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="rol",
            field=models.CharField(
                choices=[
                    ("OP", "Operator"),
                    ("SL", "Seller"),
                    ("PR", "President"),
                    ("TR", "Transport"),
                ],
                default="OP",
                max_length=20,
            ),
        ),
    ]
