# Generated by Django 4.2.11 on 2024-04-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_remove_member_daysofweek_task_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="init_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
